## This creates a setup that allows for automated revers HTTP 
## Proxy, using nginx, and the automated generation of SSL 
## certs through LetsEncrypt.

version: '2'
networks:
  proxy-net:
    external:
      name: proxy-net

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - proxy-net
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_prox
#    environment:
#      - ENABLE_IPV6=true  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/certs:/etc/nginx/certs:ro
      - ./vol/vhost.d:/etc/nginx/vhost.d
      - ./vol/html:/usr/share/nginx/html

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
